# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d4bae9ddbfaf0d6beace61d818e598b449770e487d938e7a535dfee24cd6d6c4568e02ca111ed8fadbc503c9c2edc0289faac5d84ef4f246887ccf64050e014

test:
  secret_key_base: 19f39f68c87283b9ff3375361ebf0435849e8876536505d369ae6463a2d86b159d51fc90c5a84edc6ec60a95c917ac2c1bc46c154f0d7e397095ee6c216d44ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
